### Get all products

GET http://localhost:1234/products

### Get product by category

GET http://localhost:3000/products?category=Cheesecakes

### Get product by id

GET http://localhost:1234/products/1

### Get all categories

GET http://localhost:3000/products/categories

### Create product

POST http://localhost:1234/products 
Content-Type: application/json

{
    "category": "Cheesecakes",
    "name": "Classic New York Cheesecake",
    "previewDescription": "Rich and creamy traditional cheesecake",
    "detailDescription": "Our Classic New York Cheesecake is a timeless favorite. Made with premium cream cheese, this dense and rich cheesecake has a smooth, velvety texture and a hint of vanilla. It's baked on a buttery graham cracker crust and finished with a light sour cream topping. Perfect for those who love a traditional, no-frills cheesecake.",
    "image": "https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "price": 3500
  }


### Create category

POST http://localhost:1234/products/categories
content-Type: application/json

{
  "name": "Cheesecakes"
}

### Update product

PATCH http://localhost:3000/products/4
Content-Type: application/json

{  
         "image":"carrot_cake.jpg"
      }

### Delete product

DELETE http://localhost:1234/products/1


### Get orders

GET http://localhost:1234/orders  

### Create order

POST http://localhost:3001/orders
Content-Type: application/json

{
    "name": "Aaron Avila",
    "address": "123 Main St",
    "total": 600,
    "email": "vCqR3@example.com",
    "date": "2024-08-05T17:49:26.433Z",
    "status": "Pending",
    "phone": "123456789",
      "orderItems": [
        {"productName":"Birthday cake",
        "quantity":2,
    "total":300
},{"productName":"Banana cake",
"quantity":1,
"total":300}]
}