### Get all products

GET http://localhost:3000/products

### Get product by category

GET http://localhost:3000/products?category=Cakes

### Get all categories

GET http://localhost:3000/products/categories

### Create product

POST http://localhost:3000/products
Content-Type: application/json

{  
         "name":"Avocado cake",
		 "description":"Avocado cake is a cake prepared using avocado as a primary ingredient, together with other typical cake ingredients. The avocados may be mashed, and may be used as an ingredient in cake batter, in cake toppings and alone atop a cake. Cake variations include raw avocado cake, avocado brownies and avocado cheesecake. Raw, uncooked versions of avocado cake can be high in vitamin E and essential fatty acids, which are derived from avocado. Avocado-based cake toppings include avocado fool and avocado crazy.",
         "price":300,
         "category":"Cakes"
      };

### Create category

POST http://localhost:3000/products/categories
Content-Type: application/json

{
	"name": "Ice-Creams"
}

### Update product

PATCH http://localhost:3000/products/1
Content-Type: application/json

{
    "image": "batido.png"
}

### Get orders

GET http://localhost:3000/orders  

### Create order

POST http://localhost:3000/orders
Content-Type: application/json

{
    "name": "Aaron Avila",
    "address": "123 Main St",
    "total": 600,
    "email": "vCqR3@example.com",
    "date": "2024-08-05T17:49:26.433Z",
    "status": "Delivered",
    "phone": "123456789",
      "orderItems": [
        {"productName":"Birthday cake",
        "quantity":2,
    "total":300
},{"productName":"Banana cake",
"quantity":1,
"total":300}]
}