### Get all products

GET http://localhost:1234/products

### Get product by category

GET http://localhost:3000/products?category=Cheesecakes

### Get product by id

GET http://localhost:3000/products/1

### Get all categories

GET http://localhost:3000/products/categories

### Create product

POST http://localhost:1234/products 
Content-Type: application/json

{  
  "category": "Cheesecakes",
"name":"Lemon cheesecake",
         "previewDescription":"A cheesecake made of lemon",
     "detailDescription":"Cheesecake is a sweet dessert consisting of one or more layers. The main, and thickest layer, consists of a mixture of soft, fresh cheese (typically cream cheese or ricotta), eggs, and sugar; if there is a bottom layer it often consists of a crust or base made from crushed cookies (or digestive biscuits), graham crackers, pastry, or sponge cake. It may be baked or unbaked (usually refrigerated). Cheesecake is usually sweetened with sugar and may be flavored or topped with fruit, whipped cream, nuts, cookies, fruit sauce, and/or chocolate syrup. Cheesecake can be prepared in many flavors, such as strawberry, pumpkin, key lime, chocolate, Oreo, chestnut, or toffee.",
         "image":"lemoncheese_cake.jpg",
         "price": 15
      }


### Create category

POST http://localhost:1234/products/categories
content-Type: application/json

{
  "name": "Cheesecakes"
}

### Update product

PATCH http://localhost:3000/products/4
Content-Type: application/json

{  
         "image":"carrot_cake.jpg"
      }

### Get orders

GET http://localhost:3000/orders  

### Create order

POST http://localhost:3001/orders
Content-Type: application/json

{
    "name": "Aaron Avila",
    "address": "123 Main St",
    "total": 600,
    "email": "vCqR3@example.com",
    "date": "2024-08-05T17:49:26.433Z",
    "status": "Pending",
    "phone": "123456789",
      "orderItems": [
        {"productName":"Birthday cake",
        "quantity":2,
    "total":300
},{"productName":"Banana cake",
"quantity":1,
"total":300}]
}